/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignoutImport } from './routes/signout'
import { Route as GetCalendarImport } from './routes/getCalendar'
import { Route as CalendarImport } from './routes/calendar'
import { Route as AddEntryImport } from './routes/addEntry'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const GetCalendarRoute = GetCalendarImport.update({
  id: '/getCalendar',
  path: '/getCalendar',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const AddEntryRoute = AddEntryImport.update({
  id: '/addEntry',
  path: '/addEntry',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addEntry': {
      id: '/addEntry'
      path: '/addEntry'
      fullPath: '/addEntry'
      preLoaderRoute: typeof AddEntryImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/getCalendar': {
      id: '/getCalendar'
      path: '/getCalendar'
      fullPath: '/getCalendar'
      preLoaderRoute: typeof GetCalendarImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addEntry': typeof AddEntryRoute
  '/calendar': typeof CalendarRoute
  '/getCalendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addEntry': typeof AddEntryRoute
  '/calendar': typeof CalendarRoute
  '/getCalendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/addEntry': typeof AddEntryRoute
  '/calendar': typeof CalendarRoute
  '/getCalendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addEntry' | '/calendar' | '/getCalendar' | '/signout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addEntry' | '/calendar' | '/getCalendar' | '/signout'
  id: '__root__' | '/' | '/addEntry' | '/calendar' | '/getCalendar' | '/signout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEntryRoute: typeof AddEntryRoute
  CalendarRoute: typeof CalendarRoute
  GetCalendarRoute: typeof GetCalendarRoute
  SignoutRoute: typeof SignoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEntryRoute: AddEntryRoute,
  CalendarRoute: CalendarRoute,
  GetCalendarRoute: GetCalendarRoute,
  SignoutRoute: SignoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addEntry",
        "/calendar",
        "/getCalendar",
        "/signout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addEntry": {
      "filePath": "addEntry.tsx"
    },
    "/calendar": {
      "filePath": "calendar.tsx"
    },
    "/getCalendar": {
      "filePath": "getCalendar.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
