/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignoutImport } from './routes/signout'
import { Route as GetCalendarImport } from './routes/get-calendar'
import { Route as DefaultCalendarImport } from './routes/default-calendar'
import { Route as AuthenticatedImport } from './routes/authenticated'
import { Route as AddEntryImport } from './routes/add-entry'
import { Route as AddCalendarImport } from './routes/add-calendar'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignoutRoute = SignoutImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRoute,
} as any)

const GetCalendarRoute = GetCalendarImport.update({
  id: '/get-calendar',
  path: '/get-calendar',
  getParentRoute: () => rootRoute,
} as any)

const DefaultCalendarRoute = DefaultCalendarImport.update({
  id: '/default-calendar',
  path: '/default-calendar',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AddEntryRoute = AddEntryImport.update({
  id: '/add-entry',
  path: '/add-entry',
  getParentRoute: () => rootRoute,
} as any)

const AddCalendarRoute = AddCalendarImport.update({
  id: '/add-calendar',
  path: '/add-calendar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add-calendar': {
      id: '/add-calendar'
      path: '/add-calendar'
      fullPath: '/add-calendar'
      preLoaderRoute: typeof AddCalendarImport
      parentRoute: typeof rootRoute
    }
    '/add-entry': {
      id: '/add-entry'
      path: '/add-entry'
      fullPath: '/add-entry'
      preLoaderRoute: typeof AddEntryImport
      parentRoute: typeof rootRoute
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/default-calendar': {
      id: '/default-calendar'
      path: '/default-calendar'
      fullPath: '/default-calendar'
      preLoaderRoute: typeof DefaultCalendarImport
      parentRoute: typeof rootRoute
    }
    '/get-calendar': {
      id: '/get-calendar'
      path: '/get-calendar'
      fullPath: '/get-calendar'
      preLoaderRoute: typeof GetCalendarImport
      parentRoute: typeof rootRoute
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-calendar': typeof AddCalendarRoute
  '/add-entry': typeof AddEntryRoute
  '/authenticated': typeof AuthenticatedRoute
  '/default-calendar': typeof DefaultCalendarRoute
  '/get-calendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-calendar': typeof AddCalendarRoute
  '/add-entry': typeof AddEntryRoute
  '/authenticated': typeof AuthenticatedRoute
  '/default-calendar': typeof DefaultCalendarRoute
  '/get-calendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/add-calendar': typeof AddCalendarRoute
  '/add-entry': typeof AddEntryRoute
  '/authenticated': typeof AuthenticatedRoute
  '/default-calendar': typeof DefaultCalendarRoute
  '/get-calendar': typeof GetCalendarRoute
  '/signout': typeof SignoutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-calendar'
    | '/add-entry'
    | '/authenticated'
    | '/default-calendar'
    | '/get-calendar'
    | '/signout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-calendar'
    | '/add-entry'
    | '/authenticated'
    | '/default-calendar'
    | '/get-calendar'
    | '/signout'
  id:
    | '__root__'
    | '/'
    | '/add-calendar'
    | '/add-entry'
    | '/authenticated'
    | '/default-calendar'
    | '/get-calendar'
    | '/signout'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCalendarRoute: typeof AddCalendarRoute
  AddEntryRoute: typeof AddEntryRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  DefaultCalendarRoute: typeof DefaultCalendarRoute
  GetCalendarRoute: typeof GetCalendarRoute
  SignoutRoute: typeof SignoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCalendarRoute: AddCalendarRoute,
  AddEntryRoute: AddEntryRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  DefaultCalendarRoute: DefaultCalendarRoute,
  GetCalendarRoute: GetCalendarRoute,
  SignoutRoute: SignoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-calendar",
        "/add-entry",
        "/authenticated",
        "/default-calendar",
        "/get-calendar",
        "/signout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/add-calendar": {
      "filePath": "add-calendar.tsx"
    },
    "/add-entry": {
      "filePath": "add-entry.tsx"
    },
    "/authenticated": {
      "filePath": "authenticated.tsx"
    },
    "/default-calendar": {
      "filePath": "default-calendar.tsx"
    },
    "/get-calendar": {
      "filePath": "get-calendar.tsx"
    },
    "/signout": {
      "filePath": "signout.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
